# Generated by Django 3.2.18 on 2023-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmarkfolder_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkfolder',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
