# Generated by Django 3.2.18 on 2023-04-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_alter_bookmarkfolder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfolder',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmarks.bookmarkfolder'),
        ),
    ]
