# Generated by Django 3.2.18 on 2023-04-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_bookmarkfolder_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkfolder',
            name='folder',
        ),
    ]
