# Generated by Django 3.2.18 on 2023-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_remove_bookmarkfolder_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkfolder',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
