# Generated by Django 3.2.18 on 2023-04-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_alter_bookmarkfolder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='folder',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarkfolder'),
        ),
        migrations.AddField(
            model_name='bookmarkfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarkfolder'),
        ),
    ]
